### ISSUE TITLE
Make this into a PWA

### ISSUE THREAD

**Issue by georgesoteriou** [stadians/stadians#26]
PWAs have many benefits. 
I want it because it will allow users to "install" the page as a standalone app on the device for one.
 
It is also quite simple to do. For more info look here: 
https://web.dev/progressive-web-apps/

But basically all you need to do is add a "manifest" and a "service worker".

**Comment by jeremyBanks** [comment]
TIL! I thought installable PWAs were only supported on mobile devices, I didn't realize that's what installable websites like Photopea were doing, I thought they were still using the long-deprecated Chrome Apps functionality.

Thanks for pointing this out! I probably won't get to this right away but I'll try to do it soon-ish.

When I've tried using ServiceWorkers in the past, I've often ended up confusing myself by creating weird caching bugs. So I might prefer to be conservative and only active have the ServiceWorker intercept requests inside the PWA, to reduce the scope of potential bugs to users who've opted in to install it. (Maybe if it works smoothly and isn't causing any weirdness I could generally enable it later.)

**Comment by jeremyBanks** [comment]
I took a quick stab at this (65ae3b2c604dc2ef9b3301fa8531fbdd677b5150), and it seemed to be working locally, but when I deployed it, the service worker broke the page, so I've rolled it back (f0ba7f8cf4032e2e8f46aea5d8ac3e38092bfbbe). I'll try to figure out what I did wrong later.

**Comment by georgesoteriou** [comment]
How does it break? What's the error?

**Comment by jeremyBanks** [comment]
I didn't see the error before (apparently I was looking in the wrong place). Trying again I see a pretty clear error message:

> The FetchEvent for "http://localhost:57481/#dev-tools" resulted in a network error response: an object that was not a Response was passed to respondWith().

and indeed, I was passing an async function, but not calling it, so I was passing the function itself instead of the response I was supposed to. I guess I my local testing wasn't actually exercising the service worker, but Chrome's Application debugging tab went from "doesn't work offline" to "works offline" and I assumed it was right.

Publishing the hopefully-fixed version now...

**Comment by jeremyBanks** [comment]
It seems to be working. 🙂 

The current manifest config will need some improvements -- when I launch a Stadia game, it opens in the same PWA window, but I don't have any navigation controls visible so it's not possible to get back to the launcher.

**Comment by georgesoteriou** [comment]
It works perfectly for me

![Screenshot_20200913-194143.jpg](https://user-images.githubusercontent.com/7989817/93025836-313d8a80-f5f9-11ea-969c-d34a0b959d58.jpg)

**Comment by jeremyBanks** [comment]
Okay, great. If it's working nicely for you, and sort-of working for me, I'm content to leave this here for now. For reference, some screenshots of what it looks like on desktop:

<img width="360" alt="Screen Shot 2020-09-13 at 6 03 07 PM" src="https://user-images.githubusercontent.com/18020/93029762-a73af500-f5eb-11ea-856a-66e1653f3a4d.png">

With this bar that appears when you navigate to a game, both in windowed and fullscreen:

<img width="360" alt="Screen Shot 2020-09-13 at 6 03 02 PM" src="https://user-images.githubusercontent.com/18020/93029775-b1f58a00-f5eb-11ea-8fc6-2c9db71b33c9.png">

<img width="360" alt="Screen Shot 2020-09-13 at 6 02 56 PM" src="https://user-images.githubusercontent.com/18020/93029777-b457e400-f5eb-11ea-8178-ee14c60b7fa8.png">

This seems to be standard behaviour for Chrome PWA desktop apps, at least on Mac OS, and I don't see any way to disable it, except for throwing back to the standard browser when you launch a game. Maybe it can be revisited later.

**Comment by georgesoteriou** [comment]
It might be a good idea to change all your links that point to stadia to open in a new tab to avoid that bar on top while on stadia page

**Comment by jeremyBanks** [comment]
@georgesoteriou Done! But only for Desktop PWAs, since the desktop browser experience is already fine, and I wasn't sure whether or not I should apply the change on mobile PWAs.

This is pretty nice! Thanks for the suggestion, I'm going to keep using this.

**Comment by georgesoteriou** [comment]
No worries. Yea desktop only was a good idea. Mobile works great as it just opens the stadia app. Good work! Great improvement.
