### ISSUE TITLE
Collapse outer margins if the screen is too narrow, such as on mobile

### ISSUE THREAD

**Issue by jeremyBanks** [stadians/stadians#4]
Requested/reported by @GeorgeSoteriou [on Reddit](https://www.reddit.com/r/Stadia/comments/ij4y5h/i_made_a_snappy_new_launcher_for_stadia_instantly/g3c5aye/?context=3), with [this screenshot](https://user-images.githubusercontent.com/18020/91668942-dc6d2080-eade-11ea-8ef5-4f4dba6c3915.png).

Our outer margins aren't huge, and they make sense for a horizontal view, but for a vertical or mobile view we probably want to crush them down to almost nothing. I call this a design bug. We should probably add a CSS `@media` query to change this.

**Comment by jeremyBanks** [comment]
![image](https://user-images.githubusercontent.com/18020/92180824-f330b180-ee15-11ea-9b91-c12e6708d0c9.png)

It also looks very bad on my iPhone. (Which I guess is secondary to Android since you can't play here, but it can punt you over to the official apps launcher for the game.)

**Comment by jeremyBanks** [comment]
Done as of 4a1ba5a5054b307462ff34f09f6b7cfe249c19bb. The more significant change was adjusting the default viewport size so it lined up more cleanly with a multiple of the tile size, which reduces the implicit outer margin. I also tweaked the margins slightly on small screens.

@georgesoteriou, could you confirm whether this looks any better on your phone?

**Comment by jeremyBanks** [comment]
![image](https://user-images.githubusercontent.com/18020/92267874-66d2cd00-eeaf-11ea-8060-414164f375b5.png)

On my iPhone, for what it's worth

**Comment by georgesoteriou** [comment]
Looks great! Thanks! I will use this over stadia launcher from now on :) [Screenshot_20200904-184538.jpg](https://user-images.githubusercontent.com/7989817/92270962-e330d480-eede-11ea-9c14-7652170a2400.jpg)
